// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenNone-0]
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[COMMA-5]
	_ = x[DOT-6]
	_ = x[QUESTION-7]
	_ = x[COLON-8]
	_ = x[MINUS-9]
	_ = x[PLUS-10]
	_ = x[SEMICOLON-11]
	_ = x[SLASH-12]
	_ = x[STAR-13]
	_ = x[BANG-14]
	_ = x[BANG_EQUAL-15]
	_ = x[EQUAL-16]
	_ = x[EQUAL_EQUAL-17]
	_ = x[GREATER-18]
	_ = x[GREATER_EQUAL-19]
	_ = x[LESS-20]
	_ = x[LESS_EQUAL-21]
	_ = x[PLUSPLUS-22]
	_ = x[MINUSMINUS-23]
	_ = x[IDENTIFIER-24]
	_ = x[STRING-25]
	_ = x[NUMBER-26]
	_ = x[AND-27]
	_ = x[CLASS-28]
	_ = x[ELSE-29]
	_ = x[FALSE-30]
	_ = x[FUN-31]
	_ = x[FOR-32]
	_ = x[IF-33]
	_ = x[NIL-34]
	_ = x[OR-35]
	_ = x[PRINT-36]
	_ = x[RETURN-37]
	_ = x[SUPER-38]
	_ = x[THIS-39]
	_ = x[TRUE-40]
	_ = x[VAR-41]
	_ = x[WHILE-42]
	_ = x[BREAK-43]
	_ = x[CONTINUE-44]
	_ = x[EOF-45]
}

const _TokenType_name = "TokenNoneLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTQUESTIONCOLONMINUSPLUSSEMICOLONSLASHSTARBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALPLUSPLUSMINUSMINUSIDENTIFIERSTRINGNUMBERANDCLASSELSEFALSEFUNFORIFNILORPRINTRETURNSUPERTHISTRUEVARWHILEBREAKCONTINUEEOF"

var _TokenType_index = [...]uint16{0, 9, 19, 30, 40, 51, 56, 59, 67, 72, 77, 81, 90, 95, 99, 103, 113, 118, 129, 136, 149, 153, 163, 171, 181, 191, 197, 203, 206, 211, 215, 220, 223, 226, 228, 231, 233, 238, 244, 249, 253, 257, 260, 265, 270, 278, 281}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
